### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#10]
Right now, with the `\href` command, links are formatted by LaTeX so that they are clickable. But it may not be a good idea if the PDF is printed. Therefore (and thanks to a class option?) we should have a macros that also gives the url (in parentheses? as a footnote?) if needed.

**Comment by Karnaj** [comment]
We can replace `\href` with a `externalLink` macro. This macro use `\href` or format the link (to me like in Markdown syntax) depending on a class option.

**Comment by pierre-24** [comment]
This was more or less what I had in mind. And it allow us to exchange the order of the argument from `{link}{text}` to `{text}{link}` (like in markdown)
