### ISSUE TITLE
[PDF] Font with serif on the first page

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/latex-template#100]
Sur la première page c'est volontaire de choisir une police avec serif ?

De plus les pseudos s'affichent plus "mal" que "bien", je ne les trouve pas très lisible.

![image](https://user-images.githubusercontent.com/18501150/50623336-e65b0c80-0f14-11e9-9e13-37a804d5306c.png)
![image](https://user-images.githubusercontent.com/18501150/50623361-3639d380-0f15-11e9-845c-d3b064212980.png)
![image](https://user-images.githubusercontent.com/18501150/50623406-de4f9c80-0f15-11e9-82f0-1d36d6a2773b.png)

https://github.com/zestedesavoir/zds-site/issues/5210

**Comment by pierre-24** [comment]
Plus que le *serif*, à mon avis, ce qui te chipote, c'est l'utilisation de *smallcaps*. Mais je peux faire des tests :)

**Comment by Arnaud-D** [comment]
Est-ce que ça résout aussi le fait que la ligne de base du texte n'est pas alignée ? Les pseudos ondulent sur les screenshots.

**Comment by pierre-24** [comment]
J'ai l'impression que oui:

![image](https://github.com/zestedesavoir/latex-template/assets/7889675/1dff6843-4b42-4189-b854-36146fd89c95)
