### ISSUE TITLE
\sout in titles

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#102]
Due to hyperref, it is not possible to include `\sout` (striketrough) in titles. Before sending a report to zmarkdown, I would like to try  [this](https://tex.stackexchange.com/questions/439855/soul-argument-of-xxx-has-an-extra-after-registering-custom-command-with-so) first (maybe we will need to provide a custom command, I'll check).

**Comment by artragis** [comment]
On zmd repo @Karnaj talked about wrapping the title inside `\texorpdfstring{}`. Isn't that possible on latex-template side?

**Comment by pierre-24** [comment]
This is why I would like to try this first. If not, you'll need to do it with https://github.com/zestedesavoir/zmarkdown/issues/308 :)
