### ISSUE TITLE
The "iframes"

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#11]
Right now, there is no equivalence for the videos and jsfidles (inserted by `!()` in zMD). Obviously, [and even if it is possible](https://tex.stackexchange.com/questions/1574/embedding-videos-and-animations), we would like to get a block reporting the url of the video instead of the video and a text message "to see the video, go to ...". 

Note that markdown does allow for caption on those iframes, so we should take this into account.

**Comment by artragis** [comment]
AS a matter of fact, I can also add some data to the AST so that you can make a simple "code" for the jsfiddle part and try to get presentation image for others.

**Comment by pierre-24** [comment]
The code from jsfiddle may be a good idea, though in practice there is 3 "codes" (HTML, CSS and JS) so it can be long.

On the other hand, I'm less in favor of using presentation images, since it is just an image: it does not share any information. I would rather prefer a "go there to see that".

**Comment by artragis** [comment]
It's like you want.
