### ISSUE TITLE
On a small tutorial/article, figures are not numbered

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#110]
[As seen there](https://zestedesavoir.com/tutoriels/pdf/2175/pourquoi-ca-gonfle.pdf), there is two "Figure 1.", since it comes from section one, but no number after the dot.

**Comment by Karnaj** [comment]
[Here](https://github.com/zestedesavoir/latex-template/blob/master/zmdocument.cls#L217). It should be `\arabic{figure}`. And then we have the same issue with tables (the next line).
