### ISSUE TITLE
Tables and figures

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#12]
For images:

```latex
\begin{center}
\includegraphics[width=\linewidth]{xxx}
\captionof{figure}{Légende}
\end{center}
```

+ No width ?
+ Environment ? (reduce the quantity of code to insert by the zMD parser)

For tables:

```latex
\begin{longtabu}{|c|c|c|} \hline
element & element & element\\ \hline
element & element & element\\ \hline
element & element & element\\ \hline
\caption{Légende}
\end{longtabu}
```

+ Centred alignment ? Left alignment ?
+ Every horizontal and vertical lines or only the first, second and last horizontal line ? (to differentiate the column title from the rest)
+ Bold for column title ?
+ Use of the [`booktabs` package](https://www.ctan.org/pkg/booktabs/) ?

**Comment by Karnaj** [comment]
For tables it will be more difficult but for images a command like that is good. `\image{path}{caption}` or `\image[caption]{legend}`. However, we should create two command (there is also inline images).

**Comment by pierre-24** [comment]
For inline images, `\includegraphics` is the good one. Or we can add a optional parameter `inline` to a possible `\image` command.
