### ISSUE TITLE
Support des retours à la ligne dans les codes

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/latex-template#122]
Dans le PDF du tuto Arduino (https://zestedesavoir.com/tutoriels/pdf/686/arduino-premiers-pas-en-informatique-embarquee.pdf), page 263, une ligne de code est un peu longue et n'est pas retournée à la ligne.

**Comment by Karnaj** [comment]
J'ai l'impression que ça n'arrive que pour du texte entre guillemets et seulement dans les langages où aller à la ligne dans ce cas donnerait un résultat différent dans l'exécution du code (par exemple s'il faut insérer un `\` pour pouvoir continuer à écrire la chaîne de caractères sur la nouvelle ligne). En LaTeX par exemple, le saut est fait.

**Comment by Karnaj** [comment]
L'option `breakanywhere` semble régler le problème. Je vérifie dans la semaine et je règle si c'est OK.
