### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#13]
The [`minted` environment](http://www.ctan.org/tex-archive/macros/latex/contrib/minted/) is awesome. But

+ We need to check whether it is is possible to support the highlighting of the lines (also check on the zMD side if they plan to support that)
+ It is technically possible to give a caption to a source code in the original zMD, so we need to support that.

See also [here](https://zestedesavoir.com/contenus/beta/1848/presenter-du-code-source-dans-un-document-latex/) (beta tutorial, french) to take advantage of all the possibilities of minted.

**Comment by AmarOk1412** [comment]
For the first point: https://github.com/gpoore/minted/issues/124

**Comment by Karnaj** [comment]
> It is technically possible to give a caption to a source code in the original zMD, so we need to support that.

With `listing` environment (or `captionof{listing}{caption}`).

```latex
% With float
\begin{listing}
\begin{minted}{python}
some code
\end{minted}
\caption{caption}
\end{listing}

% Without float
\begin{minted}{python}
some code
\end{minted}
captionof{figure}{caption}
```

**Comment by Karnaj** [comment]
I tried some code todays. Here, an example code.

```latex
\setminted{breaklines, breaksymbolleft=\hspace{2em}} 

\NewDocumentEnvironment{codeBlock}{O{}O{}m}{%
   \def\@codeCaption{#1}
   \VerbatimEnvironment
   \begin{center}
   \begin{minted}[highlightlines={#2}]{#3}%
}{
   \end{minted}
   \ifdefvoid{\@codeCaption}{}{\captionof{listing}{\@codeCaption}}
   \end{center}
}
```

Here, an example code.

```latex
\begin{codeBlock}{python}
def foo(bar):
    if True:
        return 42
    return 0
\end{codeBlock}

\begin{codeBlock}[légende]{python}
def foo(bar):
    if True:
        return 42
    return 0
\end{codeBlock}

\begin{codeBlock}[légende][1-2]{python}
def foo(bar):
    if True:
        return 42
    return 0
\end{codeBlock}

\begin{codeBlock}[][1, 3-4]{python}
def foo(bar):
    if True:
        return 42
    return 0
\end{codeBlock}

\begin{minted}{frame=single}{python}
def foo(bar):
    if True:
        return 42
    return 0
\end{minted}
```

But with this environment, the box is ugly when there is colored lines. Then, a second environment.

```latex
\NewDocumentEnvironment{codeBlock}{O{}O{}m}{%
   \def\@codeCaption{#1}
   \VerbatimEnvironment
   \FrameSep0.5em
   \begin{framed}\vspace{-1em}
   \begin{minted}[highlightlines={#2}]{#3}%
}{
   \end{minted}\vspace{-0.5em}
   \end{framed}
   \ifdefvoid{\@codeCaption}{}{\captionof{listing}{\@codeCaption}}
}
```
