### ISSUE TITLE
Problème de rendu de certains tableaux

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/latex-template#137]
### Comportement observé

Dans ce [PDF](https://zestedesavoir.com/billets/pdf/4313/plaidoyer-pour-la-npi-et-la-gamme-woodstock.pdf), on voit des tableaux  tout cassés, mais pas tous. Par exemple, on en voit page 8, mais d'autres sont présents tout du long.

### Comportement attendu

Tous les tableaux devraient être rendus correctement, quelque soit leur contenu, tant qu'il est raisonnable en place (le cas ici).

### Indications

Je pense que c'est un bug du template et pas de zmd, parce que les tableaux sont rendus correctement dans le HTML, ce qui fait pencher la balance vers LaTeX pour moi. Surtout que le TeX semble normal. On pourra déplacer le billet si ce n'est pas un bug pour le template.

**Comment by gilcot** [comment]
Complément d'information posté sur le [forum](https://zestedesavoir.com/forums/sujet/16540/soucis-de-pdf-generes/?page=1#p246051) : Les [tableaux simples](https://zestedesavoir.com/tutoriels/249/rediger-sur-zds/#des-tableaux-simples) ne posent pas de souci ; le problème est uniquement avec les [tableaux complexes](https://zestedesavoir.com/tutoriels/249/rediger-sur-zds/#tableaux-complexes) qui [contiennent des touches](https://zestedesavoir.com/forums/sujet/16516/tableau-de-touches/) dans le cas présent.

**Comment by StaloneLab** [comment]
Je n'avais pas vu ce ticket. Il est également reporté du côté de ZMd depuis mai : https://github.com/zestedesavoir/zmarkdown/issues/463

C'est un soucis assez complexe, qui pourrait être résolu par ZMd seul, mais idéalement on a envie que #135 soit résolu avant de trop toucher aux tableaux, donc ça implique quand même le template, je crois qu'il peut être ouvert des deux côtés.

**Comment by Karnaj** [comment]
J'ai enfin eu le temps de bien regarder tabulararray et je pense que c'est ok comme *package* pour nous. La gestion des longs tableaux et de la fusion de lignes et/ou de colonnes est plutôt bonne et les sauts de lignes sont également possibles (ce qui change de beaucoup d'autres *packages*. Un exemple avec tout ça.

```latex
\documentclass{article}
\usepackage{tabularray}

\begin{document}
\begin{longtblr}{colspec={|b{1cm}|b{1cm}|b{1cm}|b{1cm}|b{1cm}|}}
\hline
\SetCell[r=2]{c} 2 Rows & \SetCell[c=2]{b,2cm} {2 dd\\ ddd\\ Columns} & & \SetCell[r=2,c=2]{b,2cm} 2 Rows 2 Columns & \\
\hline
& 2-2 & 2-3 & & \\ \hline
3-1 & 3-2 & 3-3 & 3-4 & 3-5 \\ \hline
\SetCell[r=2]{c} 2 Rows & \SetCell[c=2]{b,2cm} 2 dd ddd Columns & & \SetCell[r=2,c=2]{b,2cm} {2 Rows\\ 2 Columns} & \\
\hline
& 2-2 & 2-3 & & \\ \hline
3-1 & 3-2 & 3-3 & 3-4 & 3-5 \\ \hline
\end{longtblr}
\end{document}
```

Ce qui ne demandera pas, je pense, de grands changements côté zmarkdown. On a `\SetCell` qui apparaît pour gérer la fusion de lignes et de colonnes, chaque colonne qui fera la taille de la page divisée par le nombre de colonnes (c'est déjà ce qu'on a pour le moment).

**Comment by StaloneLab** [comment]
Salut, super nouvelle, merci pour le travail sur ce changement ! Je regarde dès que possible comment intégrer ça dans ZMarkdown, ça devrait nous permettre de résoudre les quelques problèmes de tableau reportés dernièrement au passage. Je te contacterais en cas de soucis ;) .
