### ISSUE TITLE
Mélange des blocs de code

### ISSUE THREAD

**Issue by StaloneLab** [zestedesavoir/latex-template#140]
Salut,

je transfère ici un problème reporté par entwanne sur l'export de son tutoriel Python en PDF. Le ticket original est disponible sur le dépôt ZMarkdown ici : https://github.com/zestedesavoir/zmarkdown/issues/466.

En résumé, lorsque deux blocs de codes se suivent dans certains conditions particulières (que je ne parvient pas à déterminer), la compilation LaTeX (puisqu'il semble que le code généré soit valide) reproduit un bloc de code, déjà affiché précédemment, à la place d'un autre bloc de code, faisant fi du nouveau code à afficher.

**Comment by Karnaj** [comment]
En générant moi-même le tutoriel depuis le fichier tex et en regardant les logs, je vois qu'il n'y a pas de langage `csv`, en remplaçant le `csv` par n'importe quoi (par exemple `python` ou `md`), on n'a plus le problème.

```latex
\begin{CodeBlock}{csv}
nom,type,degats
charge,normal,20
tonnerre,foudre,50
jet-de-flotte,aquatique,40
brûlure,flamme,40
\end{CodeBlock}
\captionof{listing}{attaques.csv}
```
devient
```md
\begin{CodeBlock}{python}
nom,type,degats
charge,normal,20
tonnerre,foudre,50
jet-de-flotte,aquatique,40
brûlure,flamme,40
\end{CodeBlock}
\captionof{listing}{attaques.csv}
```

**Comment by StaloneLab** [comment]
Merci pour la réponse, je ne pense pas qu'implémenter le support LaTeX ait un grand intérêt vu la simplicité de CSV (qui n'est d'ailleurs pas même supporté en HTML), donc je propose soit une modification du contenu, soit une transformation par ZMd des langages invalides pour régler le problème.
