### ISSUE TITLE
Consistent style

### ISSUE THREAD

**Issue by Karnaj** [zestedesavoir/latex-template#20]
It could be great to have coding conventions in the README (in Contributing).

**Comment by pierre-24** [comment]
Why not, but ... Which conventions ?

+ English code ? (but our example is in French :p )
+ Lowercase/Upercase/CamelCase ? (the latter, until now)
+ Start everything by zMd ? (or not ?)
+ Other things ?

**Comment by Karnaj** [comment]
> - English code ? (but our example is in French :p )
> - Lowercase/Upercase/CamelCase ? (the latter, until now)

Maybe PascalCase for environment and camelCase for macros (but what about other macros like `\textsubscript`).

> - Start everything by zMd ? (or not ?)
> - Other things ?

To discuss?

**Comment by pierre-24** [comment]
> Maybe PascalCase for environment and camelCase for macros

Seems good to me.

> but what about other macros like \textsubscript).

It is LaTeX default, but there is no inconstancy with other packages. At least we would be consistent with ourselves. 

> To discuss?

For the "start everything with zMd", it would prevent the (improbable) collisions with other packages and make sure that everything related to this class is from a same "namespace". On the other hand, it makes environment and macro names longer and less natural (`Error` vs `zMdError`) .

**Comment by vhf** [comment]
Re: namespacing:

Since we control the whole md-latex-pdf pipeline (users cannot include their own latex packages or mess directly with the latex), I would not namespace everything. If we ever have a conflict with a package we'd like to use, we could solve it on a case by case basis.

**Comment by pierre-24** [comment]
Seems reasonable.
