### ISSUE TITLE
Nested block

### ISSUE THREAD

**Issue by Karnaj** [zestedesavoir/latex-template#22]
Now, two nested block are not cute and it’s hard to distinguish them.

```latex
\documentclass[small]{zmdocument}

\usepackage{blindtext}

\begin{document}
\begin{Information}
   \blindtext
   \begin{Information}
      \blindtext
   \end{Information}
\end{Information}
\end{document}
```

A solution is to indent text in the block. What do you think about it?

**Comment by pierre-24** [comment]
I don't indent much with LaTeX (probably because unlike python, my IDE does not indent for me). Why not, thought (related to #20, then, but we need to say exactly when to indent and when not, for example, here you didn't indent after `\begin{document}`, which I prefer). Note that it is only for us, since the zMd parser will probably not care :p

**Comment by Karnaj** [comment]
There is a misunderstanding. I was thinking about the final outcome.

![nested](https://cloud.githubusercontent.com/assets/12633306/26753622/3b8a2b00-4838-11e7-974d-4e8f5fe494b7.png)

**Comment by pierre-24** [comment]
Oh, that ? Indeed.

**Comment by Karnaj** [comment]
I obtain a good result with this code (add indentation with `\theoremindent`).

```latex
\newcommand{\newZdSbox}[3]{
   \theoremprework{~\\ \textcolor{#3}{\rule{0.6\linewidth}{1pt}}}
   \theorempostwork{\hfill \textcolor{#3}{\rule{0.6\linewidth}{1pt}} \\}
   \theoremindent=2em
   \theoremheaderfont{\scshape\hspace{-2em}}
   \theoremseparator{ ---}
   \theoremstyle{break}
   \theorembodyfont{\normalfont}
   \newtheorem*{#1}{\textcolor{#3}{#2}}
}
```

**Comment by pierre-24** [comment]
Oh, your solution is even better than mine (based on counters ^^). I test that :p

**Comment by pierre-24** [comment]
... [Or you already did](https://github.com/Karnaj/latex-template/tree/fix-22) :p

**Comment by Karnaj** [comment]
Yep. :) What do you think about the indentation length ?

**Comment by pierre-24** [comment]
It's a yes :)

![screenshot from 2017-06-03 15 36 09](https://cloud.githubusercontent.com/assets/7889675/26753994/6b83ee38-4872-11e7-9337-c368ac2899f5.png)
