### ISSUE TITLE
Deal with additionnal (and exotic) image formats

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#28]
I found [that](https://tex.stackexchange.com/a/7608) to convert, for example, the GIF images to png (without the animation, though the SO thread mention also other possibilities). For example,

```latex
\epstopdfDeclareGraphicsRule{.gif}{png}{.png}{convert gif:#1 png:\OutputFile}
\AppendGraphicsExtensions{.gif}
```

It only requires to use `convert` from the imagemagic toolbox (which is multi-platform), so I think it worth it. And it offers the possibility to use an external tool to convert SVG as well.

**Comment by vhf** [comment]
Using `convert` is reasonable for us. Could you please include this in the class for all the most common image formats?

We need to support at least `png`, `gif` and `jp(e)g` as input, and they should show up in the PDF.

**Comment by pierre-24** [comment]
What about `svg` ? It [seems possible](https://superuser.com/a/516112).

**Comment by vhf** [comment]
Yes, the bare minimum is support for `png`, `gif` and `jp(e)g`.

**Comment by pierre-24** [comment]
PNG and JP(E)G are supported by default.

**Comment by vhf** [comment]
Good, then please add support for `gif`, then we'll close this issue.

**Comment by vhf** [comment]
How would you deal with SVGs since they are user-provided and could contain malicious code?

**Comment by pierre-24** [comment]
Turn them into PNG, as we do in ZdS ? :)

**Comment by vhf** [comment]
PDF being a vector format it wouldn't be optimal.

**Comment by pierre-24** [comment]
Indeed. On the other hand, [cairosvg](http://cairosvg.org/) allow to transform SVG to PDF, which LaTeX understand, but it adds a dependencies and requires to write some python (or use `python -c "..."`). [Inkscape](https://inkscape.org/sk/doc/inkscape-man.html) also possesses such command-line option.

**Comment by vhf** [comment]
Which one if these would be safer than using ImageMagick's convert?

**Comment by pierre-24** [comment]
`convert` will rasterize the image (even if we request a PDF conversion), so that in my mind, this is the safer option (thought, indeed, not the best idea), and I don't understand your question. On the other hand, I'm not aware on what Inkscape exactly uses (but I think it is cairosvg). Plus, I hope that cairosvg is safe, since we use it in ZdS.

**Comment by vhf** [comment]
I didn't know `convert` would rasterize between two vector formats, good to know.

`cairosvg` seems to be safe, that's probably what we'll use, zds-side though.

**Comment by pierre-24** [comment]
"Bad" news here: from what I tried until now, cairosvg still rasterize the SVG before including it into PDF. But there is a tool, [rsvg-convert](https://superuser.com/a/381128),based on cairo, that does not rasterize the SVG (or, according to the comments "not entirely"). So I will still dig into cairo to see if I can get a better output, but I have an alternative.
