### ISSUE TITLE
Smilies

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#3]
Technically just an `\includegraphics{}`, may not even need a proper macro.

**Comment by Karnaj** [comment]
I think this solution could be nice.

```latex
\def\@SmileyPath{smileys}

\newcommand{\Smiley}[1]{\expandafter\def\csname#1Smiley\endcsname{\includegraphics[height=12pt]{\@SmileyPath/#1.png} }}

\renewcommand*{\do}[1]{\Smiley{#1} } 
\docsvlist{huh, smile, ...}
```

In the document.

```latex
Here smileys : \huhSmiley, \smileSmiley, \hihiSmiley, etc.
```

**Comment by pierre-24** [comment]
Waw, you are definitely good at that. This is a very elegant way <3

I think that the list of smilies is [this one](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/zmarkdown/config.js#L47-L71) (which is the same as the files [available here](https://github.com/zestedesavoir/zds-site/tree/dev/assets/smileys)).

**Comment by Karnaj** [comment]
Thanks. <3

As the code load png images, smileys like angry should be converted to be used.
