### ISSUE TITLE
Version of LaTeX should be 2017 ?

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#33]
See [this travis build](https://travis-ci.org/pierre-24/latex-template#L266-L274). Didn't get yet why we are still using 2016, since there is no version in particular requested.

**Comment by gustavi** [comment]
This could help you https://github.com/harshjv/travis-ci-latex-pdf/blob/master/.travis.yml#L3

**Comment by pierre-24** [comment]
I'm afraid that it will increase the number of useless packages installed
and therefore the time of the build. Note that this will also happens to
Zesteux de Savoir, since I used the same script.

**Comment by gustavi** [comment]
Note : it MUST works with LaTeX version on Zeste de Savoir servers (Debian 8).

**Comment by pierre-24** [comment]
Are you telling me that LateX on production server is installed trough debian package instead of installation script ?

**Comment by gustavi** [comment]
Not sure about that. But we should use debian package.

**Comment by pierre-24** [comment]
> Not sure about that. But we should use debian package.

In debian package, the version of LaTeX is, at most, 2013, while we are using 2017 here (because we have basically no other options). So, please, no :p

**Comment by gustavi** [comment]
My bad, i'm already on stretch on my personal server so I have the 2016 version ;)

**Comment by vhf** [comment]
For obvious reasons, zds-site uses on both beta and prod the same texlive distrib as the one we run our tests with via travis.

Here is the install script: https://github.com/zestedesavoir/zds-site/blob/prod/scripts/install_texlive.sh , more info in `.travis.yml` if needed.

As long as it can safely, reproducibly, reliably be installed on our servers and during zds-site travis runs, using a different latex install than the one we currently use is not an issue.

**Comment by pierre-24** [comment]
Oh, and I will do a PR on the ZdS repo to update the telive version. Because if it happens to us, it will happen to you (I'm just waiting for #40 to be ok).
