### ISSUE TITLE
Smileys command without shorthand syntax

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/latex-template#37]
It'd be easier to produce smileys in the form `\smiley{happy}` instead of declaring `\smileys{happy}` in the preamble to generate shorthand smileys syntax that are then used as `\happySmiley`.

Would it be possible to make these changes on your side?

**Comment by pierre-24** [comment]
It is quite simple to do, but the question is ... What does it changes, to use `\smiley{xxx}` instead of `\xxxSmiley` in implementation ? (true question)

**Comment by vhf** [comment]
We would have much less weird cases to cover.

There are many more valid strings `<foo>` you can use with `\smiley{foo}` than with `\<foo>Smiley`.

**Comment by pierre-24** [comment]
It makes sense (even though UTF-8 management with LaTeX is a bit funny for file path, so I will not bet that it will work for every fancy character).
