### ISSUE TITLE
Spoilers

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#4]
Some propose that the spoilers should be available at the end of the section/chapter/document, and use references with hyperlink.

**Comment by Karnaj** [comment]
I’m writing a solution with a command `\addSpoiler` and a command `\displaySpoiler`.

**Comment by pierre-24** [comment]
Nice. Maybe `\displaySpoiler` could be called automatically before every \chapter (by tweaking the corresponding `\LevelXxxTitle`) and at the end of the document ?

**Comment by Karnaj** [comment]
Yes, I will implement it.

**Comment by pierre-24** [comment]
Perfect :)
