### ISSUE TITLE
Default value for smilies path

### ISSUE THREAD

**Issue by Karnaj** [zestedesavoir/latex-template#48]
We obtain errors if we don’t with our current code. We can have `./smilies` as default path.

**Comment by vhf** [comment]
I'd rather have `smileys` than `smilies`. The latter spelling is 5-10x less commonly used, I find it hard to remember.

**Comment by pierre-24** [comment]
[Indeed](https://books.google.com/ngrams/graph?content=smileys%2Csmilies&year_start=1970&year_end=2008&corpus=15&smoothing=1&share=&direct_url=t1%3B%2Csmileys%3B%2Cc0%3B.t1%3B%2Csmilies%3B%2Cc0).

**Comment by Karnaj** [comment]
So in that case, we should also use `\smileysPath` instead of `\smiliesPath`.
