### ISSUE TITLE
The table "issue"

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#52]
+ A very useful piece of code to combine the power of [`tabulary`](https://www.ctan.org/pkg/tabulary?lang=en) (self-adjusting column width with `LCR` instead of `lcr`) and `longtable`: https://tex.stackexchange.com/a/197808
+ Then, from I understand, we will need a `\tableCell` macro, that may take as a parameter the `colspan` and `rowspan` (and translate into `\multicolumn` and `\multirow` if needed), to be close to the traditional HTML syntax.
+ To protect table, instead of using `minipage` (my initial idea), the [`adjustbox` package](http://mirror.hmc.edu/ctan/macros/latex/contrib/adjustbox/adjustbox.pdf) seems more promising to include arbitrary environement (like, for example, lists, code or other things). The idea being to embed it in the previous command.

**Comment by Karnaj** [comment]
I’m working on it. The most difficult thing is the code management. If someone has a killer idea...

**Comment by pierre-24** [comment]
At which level ?

**Comment by vhf** [comment]
We're ready on our side. Keep us posted on your progress here :)

**Comment by Karnaj** [comment]
> At which level ?

We can’t use minted in an array. `verbatim` can’t be used in `tabu`, `longtable`, etc. (but it can be used in `tabu*`).

> We're ready on our side. Keep us posted on your progress here :)

I don’t have really usable code. Could a first iteration use `\multicolumn` and `\multirow` ?

**Comment by pierre-24** [comment]
> We can’t use minted in an array. verbatim can’t be used in tabu, longtable, etc. (but it can be used in tabu*).

Even in `minipage` or `adjustbox` ?

**Comment by Karnaj** [comment]
> Even in minipage or adjustbox ?

Nope, see that https://tex.stackexchange.com/questions/119842/how-to-use-fancyvrb-verbatim-in-tabularx

**Comment by pierre-24** [comment]
Oh. I thought about that and my conclusion was that `length_of_text/number_of_column - 2*margin_of_tabular` was a "good" width, since we cannot know in advance the width. But I didn't check if it was possible to get the number of column easily.

**Comment by Karnaj** [comment]
[Here](http://texnique.fr/osqa/questions/3316/liste-de-packages-latex-dedies-aux-tableaux-avec-description-de-leur-propos) informations about arrays packages (french).

**Comment by vhf** [comment]
Any news?

**Comment by pierre-24** [comment]
In a PM (MP), @artragis told us that he was working on something :-°

**Comment by pierre-24** [comment]
By the way, @artragis, were you able to fix all of those issues on rebber side with the command already provided?

**Comment by artragis** [comment]
yep, in rebber, when you have code inside a table, we move the code.

**Comment by pierre-24** [comment]
Ok, nice. I will do some tests in the future :)

**Comment by pierre-24** [comment]
Ok, I think we are good here (still need to think about #93, though)
