### ISSUE TITLE
Don't generate empty toc

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/latex-template#57]
Would it be possible not to display the table of contents when it's empty?

Example:

* https://momo.morph.ist/out/8dd57e35-e4cf-4514-a122-71bc050bb72f.md
* https://momo.morph.ist/out/8dd57e35-e4cf-4514-a122-71bc050bb72f.tex
* https://momo.morph.ist/out/8dd57e35-e4cf-4514-a122-71bc050bb72f.pdf

If it's not possible latex-side, we'll add the heading count to the metadata passed to the latex template to simply not print `\tableofcontents` to the latex file.

**Comment by pierre-24** [comment]
There is [a package here](https://mirror.hmc.edu/ctan/macros/latex/contrib/etoc/etoc.pdf) to explore. Otherwise, we will have to store something to the .aux, but it is possible to manually count :)

**Comment by vhf** [comment]
![screen shot 2017-07-07 at 14 03 18](https://user-images.githubusercontent.com/2022803/27957125-2fcee17a-631d-11e7-94c3-77d7d5cf1e28.png)

It seems to produce weird PDFs, I wouldn't use it.

**Comment by Heziode** [comment]
This issue it is fixed zmd side.

**Comment by pierre-24** [comment]
Perfect :)
