### ISSUE TITLE
Use LuaTex

### ISSUE THREAD

**Issue by Karnaj** [zestedesavoir/latex-template#62]
Our template is efficient and the job is done. However, because of TeX complexity, we can have difficulties with some features and we can’t have a lot of contributors. With LuaTeX, we would have an easier and more readable code. Spoilers for example.

```
\documentclass{article}
\usepackage{luacode}
\usepackage{fontspec}
\usepackage[french]{babel}

\begin{luacode*}
   spoiler_list = {}
   nb_spoiler = 0
   
   function addSpoiler(code)
      spoiler_list[nb_spoiler] = code
      nb_spoiler = nb_spoiler + 1
      tex.sprint("Ici, c’est le spoiler " .. nb_spoiler)
   end
   
   function displaySpoilers()
      for i = 0, nb_spoiler - 1 do 
         tex.print("\\section{Item " .. i + 1 .. "}" .. spoiler_list[i])
      end
      spoiler_list = {}
      nb_spoiler = 0
   end
\end{luacode*}

\newcommand{\addSpoiler}[1]{\directlua{addSpoiler("\luatexluaescapestring{\unexpanded{#1}}")}}
\newcommand{\displaySpoilers}{\directlua{displaySpoilers()}}

\begin{document}
\addSpoiler{Un spoiler}
\addSpoiler{Un autre spoiler}
\addSpoiler{Et un dernier}
\displaySpoilers
\end{document}
```

**Comment by pierre-24** [comment]
I have to confess that I don't know luatex at all, just by it's name. I'm not against using it (since lua should not be a difficult language to use), but we have to be sure that the package are compatible :)

**Comment by pierre-24** [comment]
Note that according to the documentation, it supports "modern typeface" and seems to support unicode. So it would be a nice improvement.

**Comment by pierre-24** [comment]
Today, during a "real" test with an actual tutorial, pdflatex fails. @artragis uses XeTeX, with success. So we need to compare both solutions ;)

**Comment by Karnaj** [comment]
So, it should be OK for LuaTeX. Any test ?

**Comment by pierre-24** [comment]
I'll try. Appart for the possibility to use Lua, what are the difference between luatex and xetex ? (if you know them)

**Comment by Karnaj** [comment]
[They are similar](https://tex.stackexchange.com/questions/36/differences-between-luatex-context-and-xetex). A code with XeTeX should be correct with LuaTeX after few modifications.

**Comment by pierre-24** [comment]
Well, both are actually working without any change needed, as far as I had test (except, maybe, that XeTeX give some strange characters with tabs in codes). So ... Why not ?
