### ISSUE TITLE
Real life example

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/latex-template#63]
[An unsuccessful build](https://gist.github.com/anonymous/c6a9ed225f407011b107be1b2451ee38) with a TeX file generated by the actual markdown. Investigations are welcomed.

**Comment by Karnaj** [comment]
It seems due to `codeBlock` in `addSecret`...

**Comment by pierre-24** [comment]
Among other things (`\addSecret` does not exists) :-)

**Comment by Karnaj** [comment]
`addSpoiler` instead. :)

**Comment by pierre-24** [comment]
So:

+ Parser bug: `\addSecret` → `\addSpoiler`
+ Parser bug (?): insecable space (`U+202F`) before each `:`
+ Template bug: `\begin{codeBlock}` in `\addSpoiler`
+ Parser bug: `\captionof{path}` → `\captionof{figure}{path}`
+ LaTeX bug: if image is `3b9d9738-7543-4038-b8f7-42c287b99130.png.960x960_q85.jpg`, LaTeX thinks that the extension of the file is `.png.960x960_q85.jpg` o_O
+ Parser bug: some `##` where left intact in the document

**Comment by pierre-24** [comment]
@artragis and @vhf  : if you have other examples from real life tutorials or articles, feel free to gist them :)

**Comment by artragis** [comment]
@pierre-24 @Karnaj @Heziode one example here for your tests : 

 https://gist.github.com/artragis/a29b6a18d790e391ac6a7d8a4aada143 

the `images` directory : 
[images.zip](https://github.com/zestedesavoir/zds-site/files/1394683/images.zip)

**Comment by AmarOk1412** [comment]
From example in https://github.com/zestedesavoir/zds-site/pull/4733:
`jpg` images are not loading.

**Comment by Heziode** [comment]
@AmarOk1412 It is not based on the latest version of the template.

**Comment by artragis** [comment]
For youtube image it's a zmd issue, don't worry about that, normally you can compile the latex (I generated a pdf without problem).

For the last version of the template I have no method to update it for now so I don't know how to use it.

I have no way to guess the path/to/image in licence tooltip.

**Comment by Heziode** [comment]
@artragis zmd cannot know the path of licence image, can it ?

**Comment by pierre-24** [comment]
Yep, it is like the smilies, it is up to zmd to know (it would be difficult to provide images with the template anyway).

**Comment by artragis** [comment]
@Heziode We have nothing written about licence images. If this is something easily configurable, I say hurray but for now I don't know how zmd can handle licences.

@AmarOk1412 do you know how we can do this? It seems that imitating smileys can work.

**Comment by AmarOk1412** [comment]
@artragis for the youtube images, did you try with [remark-images-download](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-images-download) enabled?

For the license, I think the best way is to mimic smileys yeah.

**Comment by artragis** [comment]
For license I've got what I need.

It seems that remark-images-download is not enabled. Can you create a pr on zmd repo please?

**Comment by Heziode** [comment]
In #69 some licence image are added (in svg)

**Comment by artragis** [comment]
Yep, It will be added soon, but before, I need #69 to be accepted and my last PR on zmd to be accepted.

**Comment by pierre-24** [comment]
I think we are good here :)
