### ISSUE TITLE
Add metadata to PDF

### ISSUE THREAD

**Issue by Heziode** [zestedesavoir/latex-template#77]
Use hyperref package for adding metadata to pdf output.

Something like this:
```latex
\hypersetup{
pdfauthor={Heziode},
pdftitle={Ceci est un titre},
pdfsubject={petite description},
pdfkeywords={tuto,mot-clef, etc},
%pdfproducer={Latex with hyperref, or other system},
%pdfcreator={pdflatex, or other tool}
}
```

With data get from website (zmd side), it is possible, isn't it ?

**Comment by Karnaj** [comment]
We already  use `hypersetup` to indicate the author and the title, is would be nice to have the subject and other informations.

**Comment by artragis** [comment]
The template into which we flush data can be found on zmardown/packages/zmarkdown.

**Comment by Heziode** [comment]
Ok, so this issue can be clause.
