### ISSUE TITLE
Tables & overflow

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/latex-template#93]
Hello,

I don't know how far it is possible for you but, sometimes text in tables overflow the pdf, like in this tutorial https://zestedesavoir.com/tutoriels/pdf/2508/matomo-analytics.pdf on part 2.3.0.6. This is not adapted to reading.

If this is not possible il bare latex, how rebber can adapt it?

**Comment by pierre-24** [comment]
It seems possible: rebber currently uses [tabu](http://ctan.math.illinois.edu/macros/latex/contrib/tabu/tabu.pdf), which seems to provide options to do that (I completely forgot about that). I can check for that within a few days and communicate the eventual possible change to rebber.

Side note: the titles seems wrong, like it has skipped a level: numbering of subsections (so `#` in a content section) is always of the form `x.y.0.z`, the `0` being weird, and there is some `####` in the generated pdf. I don't know wheter it is a rebber or a zds-site bug (I completely lost track of this part of the code :'( )

**Comment by pierre-24** [comment]
That's fixed ;)
